# Generated by Django 5.0.4 on 2024-04-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_items_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=15)),
            ],
        ),
    ]
