# Generated by Django 5.0.4 on 2024-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_accessories_image_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
